VAGRANTFILE_API_VERSION = "2"

################################################################################
# check plugins
################################################################################
required_plugins = %w(vagrant-hostmanager vagrant-vbguest)

plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

################################################################################
# Global settings
################################################################################
env = 'single'
ip = '10.10.10.5'
ram = 1024

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  ##############################################################################
  # Change hosts file, both on clients and host
  ##############################################################################
  config.hostmanager.enabled           = true
  config.hostmanager.manage_host       = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline   = true

  config.vm.box                        = 'puppetlabs/centos-7.2-64-puppet'
  config.vm.box_check_update           = true
  config.ssh.insert_key                = false

  config.vm.provider :virtualbox do |vb|
    vb.name = "dns1.#{env}.vagrant"
    vb.customize [
      'modifyvm', :id,
      '--groups', '/DNS',
      '--memory', "#{ram}",
      '--cpus', 1
    ]
  end

  ###
  ### Synced directories
  ###
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../puppet/hiera", "/var/lib/hiera"
  config.vm.synced_folder "../../puppet/manifests", "/etc/puppet/environments/#{env}/manifests"
  config.vm.synced_folder "../../puppet/modules", "/etc/puppet/environments/#{env}/modules"
 
  ###
  ### Networking
  ###
  config.vm.network :forwarded_port, host_ip: "#{ip}", guest: 53, host: 53

  ### define node
  config.vm.define :dns1 do |node|
    node.vm.hostname = "dns1.#{env}.vagrant"
    node.hostmanager.aliases = %w(dns1.localdomain dns1)
    node.vm.network :private_network, ip: "#{ip}"
  end

  ###
  ### Puppet provisioning
  ###
  config.vm.provision :puppet do |puppet|
    puppet.options           = "--verbose --debug"
    puppet.environment_path  = "../../puppet/environments"
    puppet.environment       = "#{env}"
    puppet.hiera_config_path = "../../puppet/hiera.yaml"
  end
end
